spring:
  application:
    name: configuration
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

endpoints:
  restart:
    enabled: true